import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <div className="h-20">
          <Navbar />
        </div>
        <div className="h-[calc(100vh-5rem)] flex-grow py-6 md:overflow-y-auto px-6 md:px-12 lg:px-20 xl:px-32 2xl:px-48">
          {children}
        </div>
      </body>
    </html>
  );
}
